# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish to NPM

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch the last 2 commits instead of just 1. (Fetching just 1 commit would overwrite the whole history)
        fetch-depth: 2
    - name: Use Node.js (22.x)
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    - run: npm ci
    - run: npm run bump
    - name: Get last commit message
      id: last-commit
      run: |
        echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
        echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT
    # Commit changes to package.json back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_author: ${{ steps.last-commit.outputs.author }}
        file_pattern: 'package.json'
      commit_message: ${{ steps.last-commit.outputs.message }}
      commit_options: '--amend --no-edit'
      push_options: '--force'
      skip_fetch: true
    - run: npm publish --access public --loglevel verbose --dry-run
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
